name: IL6 test
models:
  - m1024
parameters:
  Biotin:
    name: Biotin BSA
    # hidden: false
  Pbs:
    name: PBS
  Nv:
    name: Neutravidin NV

stages:
  - name: Stage A
    steps:
      - duration: 10 sec
      - actions:
          - duration: 10 sec
          - duration: 10 sec
          - duration: 10 sec
      - duration: 10 sec
      - duration: 10 sec
      - duration: 10 sec
      - duration: 10 sec
      - duration: 10 sec
  - name: Stage X
    steps:
      - duration: 20 min
      - actions:
          # - confirm: Do something
          - duration: 20 min
          - duration: 5 min
      - duration: 30 min
      - duration: 20 min
  - name: Stage Y
    steps:
      - duration: 20 min
      - duration: 5 min

# stages:
#   - name: Surface chemistry
#     steps:
#       - name: Pressure initialization
#         confirm: Set pressure to 4.2 psi
#       - name: Flow biotin
#         actions:
#           - duration: 20 min
#             valves: Biotin
#           - duration: 5 min
#             valves: Pbs
#       - name: Flow neutravidin
#         actions:
#           - duration: 20 min
#             valves: Biotin
#           - duration: 5 min
#             valves: Pbs
