on: push
jobs:
  # build-ubuntu:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v2
  #     - uses: actions/setup-node@v2
  #       with:
  #         node-version: '16'
  #     - run: npm install --prefix client
  #     - run: npm run --prefix client build
  #     - run: ./app/server/build.sh
  #     - run: npm install --prefix app/electron
  #     - run: npm run --prefix app/electron build
  #     - uses: actions/upload-artifact@v3
  #       with:
  #         name: build-ubuntu
  #         path: app/electron/out/make/zip/**/*.zip
  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - run: |
          cd client
          npm install
          npm run build
          cd -
      - run: cd app/server
      - run: python -m venv env
      - run: source env/Scripts/activate
      - run: python setup.py install
      - run: pip install ../../host
      - run: pyinstaller --noconfirm main.spec
      - run: deactivate
      - run: cd -
      - run: |
          cd app/electron
          npm install
          npm run build
          cd -
      - uses: actions/upload-artifact@v3
        with:
          name: build-windows
          path: app/electron/out/make/zip/**/*.zip
